### ISSUE TITLE
MVP Roadmap

### ISSUE THREAD

**Issue by Firgrep** [systemphil/symposia#51]
Roadmap to mvp

- [x] Auth for GH, Google and Email
- [x] We need to setup google auth provider for production 
- [x] Stripe
- [x] Video upload
- [x] Text formatting with MDX Editor
- [x] Course pages #23 
- [x] Styling #56 
- [x] Deployment
- [x] prod deployment
- [x] hook up stripe
- [x] newsletter input
- [x] maintenance messages
- [x] add seo metadata (test this works with links!)
- [x] fully test stripe integration
- [x] Testing on dev deployment

Optional
- Dynamic course test pages

**Comment by Firgrep** [comment]
Dev deployment up and running with stripe and bucket. Need more thorough testing.

**Comment by Firgrep** [comment]
Prod deployment up and running. Hooked up with stripe, but needs testing. Added newletter email input and maintenance messages.

**Comment by Firgrep** [comment]
Remaining tasks moved to sphil
